name: CI Pipeline

on:
  push:
    branches: [ main, sprint-* ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./crewai_test[dev]
        
    - name: Lint with ruff
      run: |
        ruff check crewai_test/src/
        
    - name: Format check with black  
      run: |
        black --check crewai_test/src/
        
    - name: Type check with mypy
      run: |
        mypy crewai_test/src/
        
    - name: Run tests with pytest
      run: |
        pytest crewai_test/tests/ -v --cov=crewai_test --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella